name: "Deploy Static Website -- 1989"

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - '1989/**'
      - "!.github/**"

jobs:
  deploy:
    uses: chnm/.github/.github/workflows/static--deploy.yml@main
    secrets: inherit
    with:
      context_root: "1989"
      website-devl-fqdn: "static.rrchnm.org"
      website-prod-fqdn: "1989.rrchnm.org"
