name: "Deploy Static Website -- digitalcampus"
  
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - 'digitalcampus/**'
      - "!.github/**"

jobs: 
  deploy:
    uses: chnm/.github/.github/workflows/static--deploy.yml@main
    secrets: inherit
    with:
      website-devl-fqdn: "static.rrchnm.org"
      website-prod-fqdn: "digitalcampus.tv"
