name: "Deploy Static Website -- eagleeyecitizen"

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - 'eagleeyecitizen/**'
      - "!.github/**"

jobs:
  deploy:
    uses: chnm/.github/.github/workflows/static--deploy.yml@main
    secrets: inherit
    with:
      context_root: "eagleeyecitizen"
      website-devl-fqdn: "eec.dev.chnm.gmu.edu"
      website-prod-fqdn: "eagleeyecitizen.org"
