name: "Deploy Static Website -- futl"

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - 'futl/**'
      - "!.github/**"

jobs:
  deploy:
    uses: chnm/.github/.github/workflows/static--deploy.yml@main
    secrets: inherit
    with:
      context_root: "futl"
      website-devl-fqdn: "futl.dev.chnm.gmu.edu"
      website-prod-fqdn: "futl.dev.chnm.gmu.edu"
      runner_labels: '["self-hosted","IncusOS"]'
