name: "[hurricanearchive.org] Hugo Build, Release, Deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - 'hurricanearchive/**'
      - "!.github/**"

jobs:

  hugo-build-release-deploy:
    uses: chnm/.github/.github/workflows/hugo--build-release-deploy.yml@main
    secrets: inherit
    with:
      runner_labels: '["self-hosted","IncusOS"]'
      container-registry: "ghcr.io"
      container-image-name: "hurricanearchive-website"
      hugo-context-root: "hurricanearchive"
      hugo-devl-url: "https://hurricane.dev.chnm.gmu.edu"
      hugo-prod-url: "https://hurricane.dev.chnm.gmu.edu"

      build-artifact-name: "hurricanearchive-website"
      release-tag-name-type: "iso"
      tag-prefix: "hurricane-"

      website-devl-fqdn: "hurricane.dev.chnm.gmu.edu"
      website-prod-fqdn: "hurricane.dev.chnm.gmu.edu"

