name: "Deploy Static Website -- pilbarastrike"

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - 'pilbarastrike/**'
      - "!.github/**"

jobs:
  deploy:
    uses: chnm/.github/.github/workflows/static--deploy.yml@main
    secrets: inherit
    with:
      website-devl-fqdn: "static.rrchnm.org"
      website-prod-fqdn: "pilbarastrike.org"
