name: "Deploy Static Website -- resounding"

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - 'resounding/**'
      - "!.github/**"

jobs:
  deploy:
    uses: chnm/.github/.github/workflows/static--deploy.yml@main
    secrets: inherit
    with:
      context_root: "resounding"
      website-devl-fqdn: "resounding.dev.chnm.gmu.edu"
      website-prod-fqdn: "resoundingthearchives.org"
      runner_labels: '["self-hosted","IncusOS"]'
